/**
 * <ExportMenu /> — universal dropdown to export the current list as CSV / Excel / PDF.
 * Pass the already-filtered rows; empty lists warn instead of exporting.
 */
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from "@/components/ui/dropdown-menu";
import { Download, FileSpreadsheet, FileText, FileType2 } from "lucide-react";
import {
  exportToCSV,
  exportToExcel,
  exportToPDF,
  type ExportColumn,
} from "@/lib/exporters";
import { APP_NAME } from "@/lib/appConfig";
import { toast } from "sonner";

interface Props<T> {
  data: T[];
  columns: ExportColumn<T>[];
  filename: string;
  title: string;
  filtersSummary?: string;
  /** Branding line on Excel/PDF headers; defaults to APP_NAME. */
  companyName?: string;
  /** "Generated by" line on exports (e.g. the signed-in user's email). */
  generatedBy?: string;
  size?: "default" | "sm";
  variant?: "outline" | "default" | "secondary" | "ghost";
  pdfOrientation?: "p" | "l";
}

export function ExportMenu<T>({
  data,
  columns,
  filename,
  title,
  filtersSummary,
  companyName,
  generatedBy,
  size = "sm",
  variant = "outline",
  pdfOrientation = "l",
}: Props<T>) {
  const meta = {
    filename,
    title,
    companyName: companyName ?? APP_NAME,
    generatedBy,
    filtersSummary,
  };

  const handle = (kind: "csv" | "excel" | "pdf") => {
    if (!data.length) {
      toast.warning("Nothing to export");
      return;
    }
    try {
      if (kind === "csv") exportToCSV(data, columns, meta);
      if (kind === "excel") exportToExcel(data, columns, meta);
      if (kind === "pdf") exportToPDF(data, columns, meta, { orientation: pdfOrientation });
      toast.success(`Exported ${data.length} rows as ${kind.toUpperCase()}`);
    } catch (e: any) {
      toast.error(`Export failed: ${e.message}`);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant={variant} size={size} className="gap-2">
          <Download className="h-4 w-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-44">
        <DropdownMenuLabel>Export {data.length} rows</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={() => handle("csv")}>
          <FileText className="h-4 w-4 mr-2" /> CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handle("excel")}>
          <FileSpreadsheet className="h-4 w-4 mr-2" /> Excel (.xlsx)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handle("pdf")}>
          <FileType2 className="h-4 w-4 mr-2" /> PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
